apiVersion: apps/v1
kind: Deployment
metadata:
   name: helloworld-k8s-service
   labels:
    AllowContainerWithoutResourcesRequests: "true"
spec:
   selector:
    matchLabels:
      app: spring-boot-k8s
   replicas: 1
   template:
    metadata:
     labels:
      app: spring-boot-k8s
      AllowRootUserAccess: "true"
    spec:
       containers:
       - name: spring-boot-k8s
         image: cp-nexus-0.novalocal:5002/docker-image:latest
         securityContext:
           allowPrivilegeEscalation: false
           privileged: false
         ports:
         - containerPort: 88